-- MySQL Script generated by MySQL Workbench
-- Thu Mar 16 21:43:28 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema salesmanagementdb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema quanlysanpham
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema quanlysanpham
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `quanlysanpham` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `quanlysanpham` ;

-- -----------------------------------------------------
-- Table `quanlysanpham`.`chucvu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlysanpham`.`chucvu` (
  `MaCV` INT NOT NULL,
  `TenCV` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`MaCV`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quanlysanpham`.`luong`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlysanpham`.`luong` (
  `BacLuong` DOUBLE NOT NULL,
  `LuongCB` INT NOT NULL,
  `HSLuong` DOUBLE NOT NULL,
  `HSPhuCap` DOUBLE NOT NULL,
  PRIMARY KEY (`BacLuong`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quanlysanpham`.`phongban`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlysanpham`.`phongban` (
  `MaPB` INT NOT NULL,
  `TenPB` VARCHAR(45) NULL DEFAULT NULL,
  `SDTPB` VARCHAR(45) NULL DEFAULT NULL,
  `DiaChi` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`MaPB`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quanlysanpham`.`trinhdohocvan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlysanpham`.`trinhdohocvan` (
  `MaTrinhDoHocVan` INT NOT NULL,
  `TTDHV` VARCHAR(45) NOT NULL,
  `ChuyenNganh` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`MaTrinhDoHocVan`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quanlysanpham`.`nhanvien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlysanpham`.`nhanvien` (
  `MaNV` INT NOT NULL,
  `HoTen` VARCHAR(45) NOT NULL,
  `SoDienThoai` VARCHAR(45) NOT NULL,
  `GioiTinh` VARCHAR(45) NOT NULL,
  `NgaySinh` VARCHAR(45) NOT NULL,
  `DanToc` VARCHAR(45) NOT NULL,
  `QueQuan` VARCHAR(45) NOT NULL,
  `MaPB` INT NOT NULL,
  `MaTrinhDoHocVan` INT NOT NULL,
  `BacLuong` DOUBLE NOT NULL,
  PRIMARY KEY (`MaNV`, `MaTrinhDoHocVan`, `BacLuong`),
  INDEX `fk_nhanvien_phongban_idx` (`MaPB` ASC) VISIBLE,
  INDEX `fk_nhanvien_trinhdohocvan1_idx` (`MaTrinhDoHocVan` ASC) VISIBLE,
  INDEX `fk_nhanvien_luong1_idx` (`BacLuong` ASC) VISIBLE,
  CONSTRAINT `fk_nhanvien_luong1`
    FOREIGN KEY (`BacLuong`)
    REFERENCES `quanlysanpham`.`luong` (`BacLuong`),
  CONSTRAINT `fk_nhanvien_phongban`
    FOREIGN KEY (`MaPB`)
    REFERENCES `quanlysanpham`.`phongban` (`MaPB`),
  CONSTRAINT `fk_nhanvien_trinhdohocvan1`
    FOREIGN KEY (`MaTrinhDoHocVan`)
    REFERENCES `quanlysanpham`.`trinhdohocvan` (`MaTrinhDoHocVan`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quanlysanpham`.`chucvu_has_nhanvien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlysanpham`.`chucvu_has_nhanvien` (
  `chucvu_MaCV` INT NOT NULL,
  `nhanvien_MaNV` INT NOT NULL,
  PRIMARY KEY (`chucvu_MaCV`, `nhanvien_MaNV`),
  INDEX `fk_chucvu_has_nhanvien_nhanvien1_idx` (`nhanvien_MaNV` ASC) VISIBLE,
  INDEX `fk_chucvu_has_nhanvien_chucvu1_idx` (`chucvu_MaCV` ASC) VISIBLE,
  CONSTRAINT `fk_chucvu_has_nhanvien_chucvu1`
    FOREIGN KEY (`chucvu_MaCV`)
    REFERENCES `quanlysanpham`.`chucvu` (`MaCV`),
  CONSTRAINT `fk_chucvu_has_nhanvien_nhanvien1`
    FOREIGN KEY (`nhanvien_MaNV`)
    REFERENCES `quanlysanpham`.`nhanvien` (`MaNV`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `quanlysanpham`.`hopdonglaodong`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `quanlysanpham`.`hopdonglaodong` (
  `MaHD` INT NOT NULL,
  `MaNV` INT NOT NULL,
  `LoaiHD` VARCHAR(45) NOT NULL,
  `TuNgay` VARCHAR(45) NOT NULL,
  `DenNgay` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`MaHD`, `MaNV`),
  INDEX `fk_hopdonglaodong_nhanvien1_idx` (`MaNV` ASC) VISIBLE,
  CONSTRAINT `fk_hopdonglaodong_nhanvien1`
    FOREIGN KEY (`MaNV`)
    REFERENCES `quanlysanpham`.`nhanvien` (`MaNV`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
